OMAP3: PM: include 'mach/irqs.h'
This patch fixes this compile error
  CC      arch/arm/mach-omap2/cpuidle34xx.o
arch/arm/mach-omap2/cpuidle34xx.c:100: error: implicit declaration of
function 'omap_irq_pending'
make[1]: *** [arch/arm/mach-omap2/cpuidle34xx.o] Error 1

The omap_irq_pending() function is declared in
'arch/arm/plat-omap/include/mach/irqs.h'

Signed-off-by: Kim Kyuwon <q1.kim@samsung.com>