lib: fs: Fix stack frame compilation errors
Large stackframes are causing compilation failures in gcc 4.4.x.

lib/decompress_bunzip2.c: In function 'get_next_block':
lib/decompress_bunzip2.c:511: error: the frame size of 1880 bytes is
larger than 1024 bytes

fs/fuse/dev.c: In function 'fuse_notify_inval_entry':
fs/fuse/dev.c:925: error: the frame size of 1064 bytes is larger than
1024 bytes

Change-Id: I64b4ecf892f5fa441fda6a5086e9588bfcc99211
Signed-off-by: Jeff Ohlstein <johlstei@codeaurora.org>